# Claude Code CLI to OpenAI API 转换服务配置文件
server:
  host: "0.0.0.0"
  port: 8000
  debug: false
  reload: false
  cors_origins:
    - "http://localhost:3000"
    - "http://127.0.0.1:3000"
    - "*"

# Claude本地CLI配置  
claude:
  name: "Claude Code CLI (Local)"
  timeout: 60
  max_retries: 3
  # 本地Claude模型映射
  models:
    - id: "claude"
      name: "claude"
      family: "local-claude-code-cli"

# 监控和日志配置
monitoring:
  enable_metrics: true
  enable_logging: true
  log_level: "INFO"
  log_requests: true
  log_responses: false
  metrics_endpoint: "/metrics"

# 限流配置
rate_limit:
  enabled: true
  requests_per_minute: 60
  burst_size: 10

# 健康检查配置
health_check:
  endpoint: "/health"
  check_claude: true