# AI代理服务配置文件
server:
  host: "0.0.0.0"
  port: 8000
  debug: false
  reload: false
  cors_origins:
    - "http://localhost:3000"
    - "http://127.0.0.1:3000"

# 后端AI服务配置
backends:
  openai:
    name: "OpenAI"
    base_url: "https://api.openai.com/v1"
    enabled: true
    timeout: 30
    max_retries: 3
    models:
      - "gpt-4"
      - "gpt-3.5-turbo"
      - "gpt-4-turbo-preview"
  
  claude:
    name: "Claude (Anthropic)"
    base_url: "https://api.anthropic.com/v1"
    enabled: true
    timeout: 30
    max_retries: 3
    models:
      - "claude-3-opus-20240229"
      - "claude-3-sonnet-20240229"
      - "claude-3-haiku-20240307"
  
  gemini:
    name: "Google Gemini"
    base_url: "https://generativelanguage.googleapis.com/v1"
    enabled: false
    timeout: 30
    max_retries: 3
    models:
      - "gemini-pro"
      - "gemini-pro-vision"

# API密钥配置 (可通过环境变量覆盖)
api_keys:
  openai: "${OPENAI_API_KEY:}"
  claude: "${CLAUDE_API_KEY:}"
  gemini: "${GEMINI_API_KEY:}"

# 监控和日志配置
monitoring:
  enable_metrics: true
  enable_logging: true
  log_level: "INFO"
  log_requests: true
  log_responses: false
  metrics_endpoint: "/metrics"

# 限流配置
rate_limit:
  enabled: true
  requests_per_minute: 60
  burst_size: 10

# 健康检查配置
health_check:
  endpoint: "/health"
  check_backends: true